export const SEARCH_BY_DESCRIPTION = 'SEARCH_BY_DESCRIPTION';
export const SEARCH_BY_LOCATION = 'SEARCH_BY_LOCATION';
export const SEARCH_BY_FULLTIME = 'SEARCH_BY_FULLTIME';
export const SEARCH_ALL_PARAMS = 'SEARCH_ALL_PARAMS';

