const SEARCH_ALL = 'SEARCH_ALL';
const SEARCH_DESCRIPTION = 'SEARCH_DESCRIPTION';
const SEARCH_LOCATION = 'SEARCH_LOCATION';
const SINGLE_JOB_POST = 'SINGLE_JOB_POST';
const UPDATE_DESC = 'UPDATE_DESC';
const UPDATE_LOC = 'UPDATE_LOC';
const UPDATE_FULL_TIME = 'UPDATE_FULL_TIME';
